FROM python:3.5.6-stretch

ADD . /gui
WORKDIR /gui

RUN apt-get update && apt-get install -y --no-install-recommends \
    apt-utils \
    build-essential \
    dpkg-dev \
    python3.5-dev \
    libjpeg-dev \
    libtiff-dev \
    libsdl1.2-dev \
    libgstreamer-plugins-base1.0-dev \
    libnotify-dev \
    freeglut3 \
    freeglut3-dev \
    libsm-dev \
    libgtk-3-dev \
    libwebkitgtk-3.0-dev \
    libxtst-dev \
    libgtk2.0-dev \
    libwebkitgtk-dev

RUN pip install --upgrade setuptools

RUN pip install -r requirements-gui.txt

RUN pip install -U \
    -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-16.04 \
    wxPython
